FROM python:3.8-slim
COPY requirements.txt /app/requirements.txt
WORKDIR ./app
RUN pip install -r requirements.txt

COPY admin_app.py admin_app.py
COPY admin_utils.py admin_utils.py
COPY utils.py utils.py

EXPOSE 9000
CMD ["python", "admin_app.py"]
