FROM python:3.8-slim
COPY requirements.txt /app/requirements.txt
WORKDIR ./app
RUN pip install -r requirements.txt
COPY . .

RUN python process_excel.py

EXPOSE 5000
CMD python app.py

# docker build -t vincentagnes/app_proto_sodiaal:V2 .
# docker run -p 8080:5000 vincentagnes/app_proto_sodiaal:V2