version: '3'

services:
  admin:
    build:
      context: .
      dockerfile: dockerfile_admin
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data:rw

  game:
    build:
      context: .
      dockerfile: dockerfile_game
    ports:
      - "5001:5001"
    volumes:
      - ./data:/app/data:rw