FROM python:3.8.8
COPY requirements.txt /app/requirements.txt
WORKDIR ./app
RUN pip install -r requirements.txt

ENV TINI_VERSION v0.19.0
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /tini
RUN chmod +x /tini

ENTRYPOINT ["/tini", "--"]

COPY game_app.py game_app.py
COPY utils.py utils.py
COPY game_utils.py game_utils.py
COPY player.py player.py
COPY appp.py appp.py

VOLUME /app/data

EXPOSE 8050
CMD ["gunicorn", "--bind", "0.0.0.0:8050", "--workers", "4", "game_app:server"]

# docker build -t vincentagnes/app_proto_sodiaal:V2 .
# docker run -p 8080:5000 vincentagnes/app_proto_sodiaal:V2